version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8
    volumes:
      - db:/var/lib/postgresql

  server:
    build:
      context: .
      dockerfile: ./docker/DockerFile.server
    ports:
      - 8000:8000
    depends_on:
      - postgres
    volumes:
      - ./server:/app/
    command: /bin/bash -c "python manage.py runserver 0.0.0.0:8000"
  # client:
  #   build:
  #     context: .
  #     dockerfile: ./docker/DockerFile.client
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./client:/app
  #   command: /bin/bash -c "npm i && npm run dev"

volumes:
  db:
