# Generated by Django 3.0.6 on 2020-05-27 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Enter Experiment code(e.g. EX123b)', max_length=20, unique=True)),
                ('title', models.CharField(help_text='Enter Experiment full title(e.g. Full funnel test)', max_length=200)),
                ('description', models.TextField(help_text='Enter Experiment short description', max_length=1000, null=True)),
                ('impact', models.IntegerField(null=True)),
                ('confidence', models.IntegerField(null=True)),
                ('ease', models.IntegerField(null=True)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='igloo.ExperimentStatus')),
            ],
            options={
                'ordering': ['impact', 'confidence', 'ease'],
            },
        ),
    ]
