# Generated by Django 3.0.6 on 2020-05-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igloo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experiment',
            options={'ordering': ['created_at', 'updated_at', 'impact', 'confidence', 'ease']},
        ),
        migrations.AddField(
            model_name='experiment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
