# Generated by Django 3.0.6 on 2020-05-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('igloo', '0002_auto_20200527_1446'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentstatus',
            options={'verbose_name_plural': 'Experiment statuses'},
        ),
    ]
