# Generated by Django 3.0.6 on 2020-05-30 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igloo', '0005_auto_20200529_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='experimentstatus',
            options={'ordering': ['pk'], 'verbose_name_plural': 'Experiment statuses'},
        ),
        migrations.AddField(
            model_name='experimentstatus',
            name='description',
            field=models.TextField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='experiment',
            name='description',
            field=models.TextField(help_text='Enter Experiment short description', max_length=2000, null=True),
        ),
    ]
