# Generated by Django 3.0.6 on 2020-05-31 02:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('igloo', '0006_auto_20200530_1531'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(null=True)),
                ('experiment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='igloo.Experiment')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
    ]
