# Generated by Django 3.0.6 on 2020-05-31 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('igloo', '0009_auto_20200531_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentschedule',
            name='estimate_days',
            field=models.IntegerField(default=0, help_text='Planned experiment duration(days)'),
        ),
    ]
